name: onboarding_view
description: Minimalistic Onboarding pages for your Flutter applications. It will reduce your development time by 50%.
version: 0.0.2
homepage: https://github.com/metekaganmusaak/onboarding_view

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
